name: MCEngineCurrency
version: ${version}
main: io.github.mcengine.MCEngineCurrency
author: MCEngine
description: MCEngine Currency
api-version: 1.18
depen: [MCEngine]
commands:
  currency:
    description: Check, Pay coin
    usage: /currency <check||pay> <currencyType||player> <amount> <currencyType>