name: Nightly Package Publisher (Thailand Time)
true:
  schedule:
  - cron: 0 17 * * *
  workflow_dispatch: null
jobs:
  publish:
    uses: MCEngine/actions/.github/workflows/gradle/publish.yml@master
    with:
      repo-name: ${{ github.repository }}
    secrets:
      USER_GITHUB_TOKEN: ${{ secrets.USER_GITHUB_TOKEN }}
